name: 'Yarn Setup'
description: 'GitHub Action for setting up a Yarn environment. Caches dependencies for reduced execution times.'
author: 'DerYeger'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  node-version:
    description: 'The version of Node.js that will be used'
    required: true

outputs:
  cache-hit:
    description: 'Indicates a cache hit'
    value: ${{ steps.node-cache.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup Node.js
      uses: actions/setup-node@v2.4.1
      with:
        node-version: ${{inputs.node_version}}
    - name: Cache node_modules
      id: node-cache
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('./yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install dependencies
      run: yarn install
      shell: bash
