name: 'Yarn Setup'
description: 'GitHub Action for setting up a Yarn environment. Caches dependencies for reduced execution times.'
author: 'DerYeger'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  node-version:
    description: 'The version of Node.js that will be used'
    required: true

outputs:
  cache-hit:
    description: 'Indicates a cache hit'
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup Node.js
      uses: actions/setup-node@v3.5.0
      with:
        node-version: ${{inputs.node_version}}
    - name: Cache ~/.cache
      id: cache
      uses: actions/cache@v3
      with:
        path: ~/.cache
        key: ${{ runner.os }}-cache-${{ hashFiles('./yarn.lock') }}
    - name: Install
      run: yarn install --frozen-lockfile
      shell: bash
